### PR TITLE
Base Menu Heading Hiding Logic To Use Subitem Count

### PR DESCRIPTION
**Pull request by moebrowne**
Changed the logic that decides whether the menu heading should be hidden to check the number of sub items rather than doing permission checks.

### CODE REVIEW

**Comment by mikemand** [comment]
What an interesting idea! 👍

**Comment by nWidart** [comment]
This is an interesting approach indeed, but why?  We're not adding new menu items, so why make it kinda dynamic ?

**Comment by moebrowne** [comment]
It's true that this is not fixing a problem, it's more of a code improvement as it removes repeated code.

**Comment by nWidart** [comment]
Hm I don't see it as repeated as it's 3 times different permissions. At a quick glance it's clear which permissions are needed to view the menu.

With your option, while  interesting, removes this readability, in my opinion.

**Pull request closed without merging**
